services:
  - type: web
    name: binom-dots
    env: go
    buildCommand: go build -o app
    startCommand: ./app
    envVars:
      - key: PORT
        value: "8080"
      - key: RENDER
        value: "true"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    autoDeploy: true